workspace:
  base: /test
  path: oe_theme

services:
  web:
    image: fpfis/php71-build:latest
    environment:
     - DOCUMENT_ROOT=/test/oe_theme
  mysql:
    image: fpfis/mysql56
  blackfire:
    image: blackfire/blackfire
    secrets: [  blackfire_server_id, blackfire_server_token ]
  frpc-tunnel:
    image: fpfis/drone-frpc-plugin:latest
    when:
      event: [ push, pull_request, tag ]
    secrets: [ frpc_token, frpc_server ]
    environment:
      - PLUGIN_ENDPOINT=web:8080
      - PLUGIN_GEN_AUTH=yes
      - PLUGIN_DOMAIN=oetheme-${DRONE_BUILD_NUMBER}-${DRONE_JOB_NUMBER}.ci.fpfis.tech.ec.europa.eu
      - PLUGIN_URL_OUTPUT_FILE=/test/oe_theme/.frpc

matrix:
  DRUPAL_VERSION:
    - 8.6.x
    - 8.5.x
    - 8.5.x-dev

pipeline:
  npm-build:
    group: prepare
    image: node
    commands: 
      - npm install
      - npm run build

  composer-install:
    group: prepare
    image: fpfis/php71-build
    volumes:
      - /cache:/cache
    commands:
      - composer require drupal/core:${DRUPAL_VERSION=8.5.x}

  composer-sa-check:
    image: phpdrone/composer-sa-checker
    lock_file: composer.lock

  site-install:
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/run drupal:site-setup
      - ./vendor/bin/run drupal:site-install

  grumphp:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/phpunit

  behat:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/behat

  blackfire-test:
    image: blackfire/blackfire
    secrets: [ blackfire_client_id, blackfire_client_token ]
    commands:
      - source /test/oe_theme/.frpc.env
      - cp -p .blackfire.yml build/
      - cp -f scripts/drone/.htaccess build/.htaccess
      
      - blackfire build-trigger --external-id=${DRONE_REPO_OWNER}-${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}-${DRONE_JOB_NUMBER} --external-parent-id=${DRONE_REPO_OWNER}-${DRONE_REPO_NAME}-${DRONE_PREV_BUILD_NUMBER}-${DRONE_JOB_NUMBER} --http-username="$${FRP_HTTP_USERNAME}" --http-password="$${FRP_HTTP_PASSWORD}" --env=ci "$${FRP_HTTP_URL}/build/" --title="${DRONE_REPO} build ${DRONE_BUILD_NUMBER} job ${DRONE_JOB_NUMBER}" --external-url="${DRONE_BUILD_LINK}"


  before-release:
    image: fpfis/php71-build
    commands:
      - ./scripts/drone/create-release-tarball.sh
    when:
      matrix:
        DRUPAL_VERSION: 8.5.x
      event: tag

  github-release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: oe_theme-${DRONE_TAG}.tar.gz
    when:
      matrix:
        DRUPAL_VERSION: 8.5.x
      event: tag


