workspace:
  base: /test
  path: oe_theme

services:
  web:
    image: fpfis/php71-build:latest
    environment:
     - DOCUMENT_ROOT=/test/oe_theme
  mysql:
    image: fpfis/mysql56

matrix:
  DRUPAL_VERSION:
    - 8.6.x
    - 8.5.x
    - 8.5.x-dev

pipeline:
  npm-build:
    group: prepare
    image: node
    commands: 
      - npm install
      - npm run build

  composer-install:
    group: prepare
    image: fpfis/php71-build
    commands:
      - composer require drupal/core:${DRUPAL_VERSION}

  composer-sa-check:
    image: phpdrone/composer-sa-checker
    lock_file: composer.lock

  site-install:
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/run drupal:site-setup
      - ./vendor/bin/run drupal:site-install

  grumphp:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/phpunit

  behat:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/behat

  before-release:
    image: fpfis/php71-build
    commands:
      - ./scripts/drone/create-release-tarball.sh
    when:
      event: tag

  github-release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: oe_theme-${DRONE_TAG}.tar.gz
    when:
      event: tag
